Iter8
semnovik/short_url pull request #11
Opened 2022-12-18 16:39 UTC by semnovik

2022-12-20 03:53 UTC, capsulated requested changes
...

2022-12-20 03:53 UTC, capsulated commented on cmd/shortener/main.go
> -	viper.AddConfigPath("configs")
`viper` решил выпилить? )))

2022-12-20 03:53 UTC, capsulated commented on cmd/shortener/main.go
> +func initFlags() {
Если пакет конфига есть, то `initFlags()` лучше перенести в него, так как это его область ответственности (Single Responsibility Principle из SOILD)

2022-12-20 03:53 UTC, capsulated commented on internal/repository/file_with_urls
> +{"UUID":"w4AWe","URL":"https://pikabu.ru"}
Данные коммитить в гит - очень плохая привычка. А ещё ключи, значение переменных окружения, токены и тому подобное. В `.gitignore` такие файлики добавить обязательно, а из репозитория удалить. По-хорошему, из истории `git` тоже удалить бы, но это сложно.

Вообщм, необходимо привыкнуть подобне не коммитить и, тем более, не пушить

2022-12-20 03:55 UTC, capsulated requested changes
Реализацию хранения файл/память необходимо переписать

Текущее решение с проверкой флага при записи/чтении "недолговечно": как только понадобится несколько методов для работы с хранилищем, например. В каждом из них нужно будет проверять флаг и добавлять запись в файл. А если ещё что-то изменится в процессе записи в файл? Каждый метод нужно будет переписать. И тест к каждому методу =(

_Такой подход реализуется на основе интерфейсов и нескольких реализациях на основе этого интерфеса_
В нашем случа необходимы две разные структуры, типа `FileStorage` и `MemStorage`. Можно сделать родительскую `Storage` и с помощью встраивания расширить. И эти  стурктуры должны удовлетворять одному интерфейсу `Storager`. И там, где они передаются в качестве зависимостей - описывать тип интерфейсом (а не указателем `*Storage`)

Если нужно подробнее - пиши в личным сообщением, выберем время для 1-1, я всё расскажу. Исправлять не много, но тут главное разобраться с этим

2022-12-20 16:00 UTC, semnovik commented
> Реализацию хранения файл/память необходимо переписать
> 
> Текущее решение с проверкой флага при записи/чтении "недолговечно": как только понадобится несколько методов для работы с хранилищем, например. В каждом из них нужно будет проверять флаг и добавлять запись в файл. А если ещё что-то изменится в процессе записи в файл? Каждый метод нужно будет переписать. И тест к каждому методу =(
> 
> _Такой подход реализуется на основе интерфейсов и нескольких реализациях на основе этого интерфейса_ В нашем случа необходимы две разные структуры, типа `FileStorage` и `MemStorage`. Можно сделать родительскую `Storage` и с помощью встраивания расширить. И эти стурктуры должны удовлетворять одному интерфейсу `Storager`. И там, где они передаются в качестве зависимостей - описывать тип интерфейсом (а не указателем `*Storage`)
> 
> Если нужно подробнее - пиши в личным сообщением, выберем время для 1-1, я всё расскажу. Исправлять не много, но тут главное разобраться с этим

Тут, кажется, понял о чем речь, есть некоторые сомнения, что реализовал правильно 👍

2022-12-20 16:00 UTC, semnovik commented on internal/repository/file_with_urls
> +{"UUID":"w4AWe","URL":"https://pikabu.ru"}
Понял, спасибо.
Выпилил

2022-12-20 16:01 UTC, semnovik commented on cmd/shortener/main.go
> -	viper.AddConfigPath("configs")
Да, выпилил, решил использовать ровно то, что советовали в рамках курса :)

2022-12-21 18:30 UTC, capsulated approved these changes
Не совсем то, что нужно. Но апрувлю. В следующем спринте появится проблема со `Storage` - пиши в директ для 1-1 - объясню подробнее

Идея приблизительно, такая: нужно использовать паттерн `фабрика`, пример тут, но нейминг интерфейса не оч (писал уже в группе)

2022-12-22 07:14 UTC, merged