Iter3
semnovik/short_url pull request #3
Opened 2022-11-26 15:51 UTC by semnovik

2022-11-30 23:00 UTC, capsulated requested changes
Классно, что сразу появилось понимания объектов в го, структуры, их конструкторы, интерфейс. И не переусложненный код - будет удобно развивать кодовую базу проекта

Но есть, что исправить: написал в комментах

2022-11-30 23:00 UTC, capsulated commented on cmd/shortener/main.go
> +	var URLStorage []string
А зачем тут объявлять? Тем более передаётся только в конструктор `repository`. Поэтому, можно инкапсулировать в пакет, чтобы при использовании максимально скрыть реализацию

2022-11-30 23:00 UTC, capsulated commented on cmd/shortener/main.go
> +	Repository := repository.NewRepository(URLStorage)
Имена переменных с большой буквы определяют глобальную область видимости. В данном случае, эти объекты не экспортируются для внешних пакетов, поэтому их лучше сделать внутренними (**private** аналогия из других языков, типа java, ts, c# и тп)

2022-11-30 23:00 UTC, capsulated commented on cmd/shortener/main.go
> +	err := http.ListenAndServe(":8080", Handler.InitRouter())
Инициализацию роутов лучше в конструкторе роутера делать. И передавать уже инициализированный роутер серверу

Также, переменные конфига сервера, в данном случае - порт, лучше вынести в константу

2022-11-30 23:00 UTC, capsulated commented on internal/app/handlers/handler.go
> +func NewHandler(service *service.Service) *Handler {
В вызове передаётся `server`, а параметр в конструкторе - `service`. Это создаёт путаницу. Нужно называть идентично, чтобы не запутаться. Либо интерфейс, если могут передаваться различные типы, которые нужно обобщить

2022-11-30 23:00 UTC, capsulated commented on internal/app/handlers/handler.go
> +func (h *Handler) InitRouter() http.Handler {
Инициализацию в контруктор лучше перенести, конструкторы как раз для этого

2022-11-30 23:00 UTC, capsulated commented on internal/app/handlers/start_page.go
> +package handlers
Имя `start_page` вводит в заблуждение. Кажется, что в этом файле реализуется html шаблон для страницы. 

А это скорее эндпоинты или хендлеры или что-то похожее

2022-11-30 23:00 UTC, capsulated commented on internal/app/repository/repositories.go
> +func NewRepository(storage []string) *Repository {
"Про запас" создавать репозиторий, в котором, возможно, появяться дополнительные репозитории - плохая практика. Если нет необходимости использования разных репозиториев, то одного вполне достаточно, `RepoURL` в нашем случае

2022-11-30 23:00 UTC, capsulated commented on internal/app/repository/url_repo.go
> +	return r.URLs[id-1], nil
Хитро)) В задаче не предусмотрено удаление, поэтому такой подход сработает. Это не ошибка, переписывать не нужно, так как тесты проходят. Но реальные задачи, обычно, реализуют минимум CRUD. И лучше, например, uuid генерировать

2022-11-30 23:00 UTC, capsulated commented on internal/app/service/service.go
> +func NewServer(repos *repository.Repository) *Service {
`NewServer`, а возвращает `Service`. Нужно что-то одно выбрать)

2022-11-30 23:00 UTC, capsulated commented on internal/app/service/service.go
> +		ShorterService: NewShorter(repos),
А вот конструкторы в конструкторе вызывать не очень хорошая идея (есть исключения, например, паттерн фабрика, но это не про наш случай). Лучше создать на родительском уровне и передать конструктору экземпляр в параметрах

2022-11-30 23:00 UTC, capsulated commented on internal/app/service/shorter.go
> +func (s *Shorter) PostURL(url string) string {
Мне кажется, лишняя абстракция. Эта логика реализуется в хендлерах с использованием репозитория. 

Такие объекты - это отличный способ реализовывать различные утилиты, которые обычно складывают в один пакет, типа utils (что является плохой практикой). Поэтому, нужно создавать подобные объекты, которые выполняют различные преобразования. И под каждую задачу - лучше свой объект-стурктуру, которая выполняет какие-то действия. И передавать их в констуркторы объектов, где требуется их использование

2022-12-08 16:54 UTC, capsulated requested changes
Некоторые замечания не исправлены, при этом обоснования, почему не исправлены - нет. Нужно либо одно, либо другое. Остальная часть замечаний исправлены.

И на пару моментов обратить внимание, написал в комментариях

2022-12-08 16:54 UTC, capsulated commented on cmd/shortener/main.go
> +	handler := handlers.NewHandler(service)
Лучше их одинаково именовать: 
```go
repository := <имя_пакета>.NewRepository()
shorter := <имя_пакета>.NewShorter(...)
handler := <имя_пакета>.NewHandler(...)
```

Так путаницы будет немного меньше))

2022-12-08 16:54 UTC, capsulated commented on internal/app/handlers/handler.go
> +func NewHandler(service services.ShorterService) http.Handler {
Интерфейс возвращается к конструкторе? Вполне возможно такое делать, но нужно понимать, почему именно интерфейс, а не экземпляр. Входные параметры очень часто описывают интерфейсом, особенно в конструкторах. Интерфейсом описывать выходные данные - это исключительные случаи и нужно понимать, для чего именно такая реализация.

Большинство случаев - принимаем интерфейс, возвращаем указатель на эксземпляр

2022-12-08 16:54 UTC, capsulated commented on internal/app/handlers/start_page.go
> +package handlers
`start_page` остался? Очень неподходящее имя для этого. Если не согласен - пиши комент, так как нужно обосновать, почему такое имя нужно оставить

2022-12-08 16:54 UTC, capsulated commented on internal/app/handlers/handler.go
> +type handler struct {
Импортируемый тип `http.Handler` - это интерфейс, `-er` по соглашению коммьюнити. Во всех стандартных библиотеках го и исходных кодах используется такое соглашение.

В нашем случае получился идентичный нейминг, но тип - структура. Так же, вносит путаницу при чтении и использовании

2022-12-08 16:54 UTC, capsulated commented on internal/app/repositories/repositories.go
> +	r.URLs[string(randUUID)] = url
А если существует уже такой же ключ? 😱

2022-12-08 16:54 UTC, capsulated commented on internal/app/repositories/repositories.go
> +		{
Что-то страшное произошло со скобками)))) По-моему, одни лишние

2022-12-08 16:54 UTC, capsulated commented on internal/app/services/service.go
> +package services
`services` - очень плохой нейминг. Так как совсем ничего не сообщает нам при чтении, какая у него область ответственности. Лучше уточнить

2022-12-08 16:54 UTC, capsulated commented on internal/app/services/service.go
> +type ShorterService interface {
Всё же это лишняя обёртка над репозиторием, как мне кажется. Или может я что-то не так понял. Мне кажется, вполне возможно использовать `Repository` непосредственно в хендлерах. Без `Service`. Или нет?

Может лучше просто: 
```go
type Shorter interface { ... }
```

Тем более, это интерфейс, и при использовании по имени не будет очевидно, что это интерфейс.

2022-12-08 16:54 UTC, capsulated commented on internal/app/services/service.go
> +type ShorterService interface {
А я уже писал об этом в прошлом ревью.

Нужно либо обосновать текущий выбор, либо исправить

2022-12-08 19:35 UTC, semnovik commented on internal/app/services/service.go
> +type ShorterService interface {
Решил сделать таким образом, чтобы на слое репозитория иметь наименьшее количество логики, т.е. чтобы репозиторий не занимался генерацией UUID'а и всего тому подобному, чтобы все что происходило на слое репозитория - это работа с хранилищем.

Это сейчас поправил: убрал со слоя репы генерацию uuid'а

Ну и с оглядкой на будущее, если будем переходить на БД, то на слое с логикой приложения не придется ничего менять

2022-12-08 20:34 UTC, semnovik commented on cmd/shortener/main.go
> +	handler := handlers.NewHandler(service)
```go
repository := storage.NewURLRepository()
shorterService := service.NewShorter(repository)
srv := server.New(shorterService)
```
Тут у меня логика следующая: имя пакета - это конкретный слой приложения.
Storage отвечает за хранение, в этом пакете может быть реализовано несколько различных видов репозиториев: например репозиторий-мапа, репозиторий-postgres и т.д. Нейминг конструктора отображает тип создаваемого мной репозитория

2022-12-08 20:52 UTC, semnovik commented on internal/app/handlers/handler.go
> +type handler struct {
Данная структура handler содержит данные, которые необходимы для обработчиков GetFullURL, SendURL. 
В том что они являются методами этой структуры (handler.GetFullURL) есть семантический смысл и это сходу читается/понимается, более подходящего имени мне не приходит в голову

2022-12-08 20:53 UTC, semnovik commented on internal/app/handlers/handler.go
> +type handler struct {
Как вариант - переименовать ее в server, но это тоже противоречит соглашению

2022-12-09 15:43 UTC, capsulated requested changes
С `service` нужно что-то сделать - он там явно лишний.
Ну и мелочь - нейминг конструктора сервера

Всё остальное - супер, как надо 👍

Назначай 1-1, пиши в личку, я только всё расскажу и объясню, почему именно так, если сомневаешься. Мы не ругаем на созвонах, да и везде, у нас такой практики нет, в принципе))) И также, в чате комьюнити и задавать вопросы, почему именно так - только приветствуется. Смело можно меня тегать, скидывать куски кода и спрашивать

2022-12-09 15:43 UTC, capsulated commented on internal/app/handlers/handler.go
> +type handler struct {
Да понятно, что это такое) Но соглашение о нейминге `-er` во всех исходниках го, и стандартных библиотеках. Мы в своём проекте можем использовать `http.Handler` из пакета `net/http` - какой у него тип?

Да, поосто переименовать так, как обычно в го структуры именуют. Для примера: пакет [net/http](https://cs.opensource.google/go/go/+/refs/tags/go1.19.4:src/net/http/server.go) - отличный подопытный для изучения стиля кода. Да и все сорсы, в принципе.

Можно `Router`, `Mux`, `Handlers`, `ShortenerHttpHandle`, `ShortenerEndpoints` и тд и тп. Много разных вариантов, да любой, в принципе, который однозначно говорит о сущности и без `-er` окончания. Но не сервер! У сервера разве не другая область ответсвенности?

2022-12-09 15:43 UTC, capsulated commented on internal/service/shorter.go
> +
А для чего две одинаковые переменные для функции с разными именами `genUUID` `generateUUID`?

2022-12-09 15:43 UTC, capsulated commented on internal/service/shorter.go
> +package service
Пакет `service` точно лишний, я так и не понял зачем он? `Repository` всё это делать должен. И генерацию ID тоже в `Repository`. И в итоге это `Repository` или `Storage`?

2022-12-09 15:43 UTC, capsulated commented on internal/server/server.go
> +func New(service service.Shorter) *http.Server {
`NewServer(...`

2022-12-09 15:43 UTC, capsulated commented on internal/server/server.go
> +	h := &handler{Service: service}
Хендлерам репозиторий передать и всё. Лишний уровень `Service`. Если бы был функционал, которому требуется дополнительный уровень абстракции - тогда да, нужно описывать. Если нет - то добавлять не нужно. Желание предусмотреть будущее и заранее подготавливать кодовую базу - реализуется за счёт использования интерфейсов, максимально независимых пакетов с минимизацией связанности, и чёткого деления на структуры и функционала по областям их ответственности

Есть вероятность, что ты используешь какой-то паттерн, но он либо реализован неправильно, либо не нужен в данной реализации 🤷‍♂️ Экспериментировать с шаблонами и паттернами на новом синтаксисе очень опасно. Лучше от простого к сложному - сначала изучить базовые подходы и синтаксис, затем уже экспериментировать с фреймворками (которые не рекомендует сообщество), шаблонами и подходами

2022-12-09 15:58 UTC, semnovik commented on internal/service/shorter.go
> +
```go
genUUID = func() string {
				return test.sendUUID
			}
```
Чтобы мокать в тестах

2022-12-09 17:10 UTC, semnovik commented on internal/server/server.go
> +	h := &handler{Service: service}
Попробовал - согласен, действительно выглядит логично) После различных видосов на ютубе, почему-то взял за аксиому, что слоев должно быть 3, переделал.

2022-12-09 17:13 UTC, semnovik commented on internal/service/shorter.go
> +
"Но не сервер! У сервера разве не другая область ответсвенности?"
Почему-то не получается отставить коммент к предыдущему комменту, где были замечания к тому, что пакет обозвал как server, но считаю, что это название для него логичное - там один из ключевых моментов это конструктор, который возвращает именно сервер

2022-12-13 05:04 UTC, capsulated approved these changes
Отлично, всё супер! 🔥

2022-12-13 06:28 UTC, merged